[package]
name = "rabbit-say-hello"
version = "0.1.0"
authors = ["douglas"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
amiquip = { version = "0.4", default-features = false }